# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 13:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('un', 'Unpublished'), ('pu', 'Published')], max_length=2)),
                ('title', models.CharField(max_length=1000)),
                ('slug', models.CharField(max_length=1000)),
                ('lede', models.TextField(blank=True, default='')),
                ('text', models.TextField(blank=True, default='')),
                ('activeTitle', models.CharField(blank=True, default='', max_length=1000)),
                ('activeSlug', models.CharField(blank=True, default='', max_length=1000)),
                ('activeLede', models.TextField(blank=True, default='')),
                ('activeText', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=1000)),
                ('link', models.CharField(blank=True, default='', max_length=1000)),
                ('tagline', models.CharField(blank=True, default='', max_length=1000)),
                ('image', models.FileField(blank=True, upload_to='game_images/')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('social', models.TextField(blank=True, default='')),
                ('bio', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='steampunkgames.Game'),
        ),
        migrations.AddField(
            model_name='entry',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL),
        ),
    ]
