# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steampunkgames', '0004_auto_20161208_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='tagline',
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
