# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steampunkgames', '0007_auto_20161209_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='activeSlug',
            field=models.SlugField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(max_length=1000),
        ),
    ]
