# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steampunkgames', '0009_entry_splashimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='squareThumbImage',
            field=models.FileField(blank=True, upload_to='square_thumb_images/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
